# Generated by Django 4.0.1 on 2022-02-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0002_rename_name_brand_name_rename_orgin_brand_orgin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
