# Generated by Django 4.0.1 on 2022-01-30 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='Orgin',
            new_name='orgin',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Descreption',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Expir_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Price',
        ),
        migrations.AddField(
            model_name='products',
            name='descreption',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='expir_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
